import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { fetchNbu, filterAssets, type Snapshot } from '@ovdp/market-data';
import initial from '../../web/data/nbu-snapshot.json';
const formatDate = (value: string) => value.split('-').reverse().join('.');
export default function CatalogScreen() {
  const [snapshot, setSnapshot] = useState(initial as Snapshot); const [query, setQuery] = useState(''); const [currency, setCurrency] = useState(''); const [refreshing, setRefreshing] = useState(false); const [today, setToday] = useState('2026-09-21');
  useEffect(() => setToday(new Date().toISOString().slice(0,10)), []);
  const rows = useMemo(() => filterAssets(snapshot.assets, { query, currency, activeOnly: true, today }), [snapshot, query, currency, today]);
  const analysis = useMemo(() => ({ counts: ['UAH','USD','EUR'].map(value => `${value} ${rows.filter(item => item.currency === value).length}`).join(' · '), next: rows[0] ?? null }), [rows]);
  async function refresh() { setRefreshing(true); try { setSnapshot(await fetchNbu()); } finally { setRefreshing(false); } }
  return <View style={styles.screen}><Text style={styles.kicker}>ПУБЛІЧНІ ДАНІ · ЛОКАЛЬНИЙ ЗАСТОСУНОК</Text><Text style={styles.title}>Каталог{ '\n' }ОВДП</Text><Text style={styles.caption}>Довідник НБУ. Пошук і фільтри працюють на пристрої.</Text><View style={styles.card}><TextInput accessibilityLabel="Пошук ISIN" value={query} onChangeText={setQuery} placeholder="Пошук за ISIN" style={styles.input} autoCapitalize="characters"/><View style={styles.chips}>{['','UAH','USD','EUR'].map(value=><Pressable key={value||'all'} onPress={()=>setCurrency(value)} style={[styles.chip, currency===value && styles.chipActive]}><Text style={currency===value ? styles.chipTextActive : styles.chipText}>{value || 'Усі'}</Text></Pressable>)}</View><Text style={styles.count}>{rows.length} випусків · знімок {snapshot.retrievedAt.slice(0,10)}</Text></View><View style={styles.analysis}><Text style={styles.analysisTitle}>Локальний аналіз вибірки</Text><Text style={styles.analysisText}>{analysis.counts}</Text><Text style={styles.analysisMuted}>{analysis.next ? `Найближче погашення: ${formatDate(analysis.next.maturityDate)} · ${analysis.next.isin}` : 'Змініть фільтри для аналізу.'}</Text></View>{refreshing && <ActivityIndicator color="#165d45"/>}<FlatList data={rows.slice(0,50)} keyExtractor={item=>item.isin} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={styles.list} renderItem={({item})=><View style={styles.row}><View style={styles.rowTop}><Text style={styles.isin}>{item.isin}</Text><Text style={styles.currency}>{item.currency}</Text></View><Text style={styles.description}>{item.description}</Text><View style={styles.rowBottom}><Text>Погашення {formatDate(item.maturityDate)}</Text><Text style={styles.rate}>{item.nominalRate ? `${item.nominalRate}%` : '—'}</Text></View></View>}/></View>;
}
const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:'#f5f6ef',paddingTop:64,paddingHorizontal:18}, kicker:{fontSize:10,letterSpacing:1.5,color:'#165d45',fontWeight:'700'}, title:{fontSize:42,lineHeight:43,color:'#172e2a',fontWeight:'700',marginTop:14}, caption:{fontSize:15,lineHeight:22,color:'#596d66',marginVertical:16}, card:{backgroundColor:'#fff',borderRadius:16,padding:14,marginBottom:12}, input:{backgroundColor:'#f5f7f3',borderRadius:10,padding:14,fontSize:16,color:'#172e2a'}, chips:{flexDirection:'row',gap:8,marginTop:12}, chip:{borderWidth:1,borderColor:'#b8cbb9',borderRadius:20,paddingVertical:8,paddingHorizontal:13},chipActive:{backgroundColor:'#165d45'},chipText:{color:'#165d45'},chipTextActive:{color:'#fff'},count:{fontSize:12,color:'#596d66',marginTop:13},analysis:{backgroundColor:'#e6f0e8',borderRadius:14,padding:16,marginBottom:12},analysisTitle:{fontSize:11,fontWeight:'700',letterSpacing:1,color:'#165d45'},analysisText:{fontSize:18,fontWeight:'700',color:'#172e2a',marginTop:8},analysisMuted:{fontSize:12,color:'#596d66',marginTop:6},list:{paddingBottom:30},row:{backgroundColor:'#fff',borderRadius:14,padding:16,marginBottom:9},rowTop:{flexDirection:'row',justifyContent:'space-between'},isin:{fontWeight:'700',color:'#172e2a',fontSize:15},currency:{fontWeight:'700',color:'#165d45'},description:{fontSize:12,color:'#596d66',marginTop:5},rowBottom:{flexDirection:'row',justifyContent:'space-between',marginTop:14,fontSize:12},rate:{fontSize:18,color:'#165d45',fontWeight:'700'} });
